insert into Users (username,userpass, name, description, email) values ('ferran.diaz',MD5('1234'), 'Ferran', 'I am batman', 'ferran.diaz@netsound.sound');
insert into User_roles values('1', 'registered');
insert into Users (username,userpass, name, description, email) values ('alejandro.jimenez',MD5('1234'), 'Alejandro', 'Cuddly bear', 'alejandro.jimenez@netsound.sound');
insert into User_roles values('2', 'registered');
insert into Users (username,userpass, name, description, email) values ('ernest.espinola',MD5('1234'), 'Ernest', 'Computer not working', 'ernest.espinola@netsound.sound');
insert into User_roles values('3', 'registered');
insert into  Follow values('1','2');
insert into  Follow values('1','3');
insert into  Follow values('3','1');
insert into Follow values('3', '2');
insert into Stings (userid, content) values ('1', 'Mensaje1');
insert into Stings (userid, content) values ('1', 'Mensaje2');
insert into Stings (userid, content) values ('1', 'Mensaje3');
insert into Stings (userid, content) values ('2', 'Sting1');
insert into Stings (userid, content) values ('2', 'Sting2');
insert into Stings (userid, content) values ('3', 'Corred insensatos');
insert into Stings (userid, content) values ('3', 'May the force be with you');
